<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Anna Bardenhagen" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project1</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">Project1</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="background" class="section level2">
<h2>Background</h2>
<p>For this project, I decided to look at two datasets: the percentage of breastfed infants by state, and the monthly average number of persons participating in Supplemental Nutrition Assistance Program (SNAP) by state. These datasets were from KFF.org, a website by the Kaiser Family Foundation that contains a large amount of health and demographic data by state. The &quot;Breastfed&quot; dataset contains four variables: one for location, which lists the states and territories (excluding Puerto Rico) in the US, and three which represent the proportion of infants in each state that were breastfed at three timepoints: at six months, at twelve months, and at any point. The &quot;SNAP&quot; dataset contains three variables: location, which also lists the states and territories in the US, the total residents in the state, and the average number of monthly SNAP participants in the state. I am interested in women's health issues, including maternal issues such as breastfeeding, and wanted to see if there was any relationship between breastfeeding and the number of SNAP recipients, which can be treated as a demographic of people of low socioeconomic status, in states. I expect to see associations between high amounts of SNAP recipients and low rates of breastfeeding; this is based on a stigma against breastfeeding which is more common in areas with low socioeconomic status, as well as the realities that people relying on SNAP benefits may face different struggles in breastfeeding, such as external stressors, poor nutrition, and work restrictions.</p>
<pre class="r"><code>library(tidyverse)
Breastfed &lt;- read_csv(&quot;Breastfed.csv&quot;)
SNAP &lt;- read_csv(&quot;State SNAP Population.csv&quot;)

head(Breastfed)</code></pre>
<pre><code>## # A tibble: 6 x 4
##   Location      Ever_Breastfed Breastfeeding_at_6_mont… Breastfeeding_at_12_mon…
##   &lt;chr&gt;         &lt;chr&gt;          &lt;chr&gt;                    &lt;chr&gt;                   
## 1 United States 0.841          0.583                    0.353                   
## 2 Alabama       0.69           0.385                    0.216                   
## 3 Alaska        0.919          0.674                    0.439                   
## 4 Arizona       0.899          0.649                    0.393                   
## 5 Arkansas      0.701          0.431                    0.238                   
## 6 California    0.903          0.671                    0.433</code></pre>
<pre class="r"><code>head(SNAP)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   Location      Total_Residents Average_Monthly_SNAP_Participants
##   &lt;chr&gt;                   &lt;dbl&gt; &lt;chr&gt;                            
## 1 United States       318498500 39651687                         
## 2 Alabama               4752600 766681                           
## 3 Alaska                 709100 91995                            
## 4 Arizona               7004300 845733                           
## 5 Arkansas              2921300 372451                           
## 6 California           38745900 3949535</code></pre>
</div>
<div id="joining-the-datasets" class="section level2">
<h2>Joining the Datasets</h2>
<p>I began by joining the datasets; I chose a full join, but since each dataset had exactly the same number of states, any join would've resulted in the same result. No data was lost in the joining process.</p>
<pre class="r"><code>fullset &lt;- full_join(Breastfed, SNAP, by = &quot;Location&quot;)
head(fullset)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   Location Ever_Breastfed Breastfeeding_a… Breastfeeding_a… Total_Residents
##   &lt;chr&gt;    &lt;chr&gt;          &lt;chr&gt;            &lt;chr&gt;                      &lt;dbl&gt;
## 1 United … 0.841          0.583            0.353                  318498500
## 2 Alabama  0.69           0.385            0.216                    4752600
## 3 Alaska   0.919          0.674            0.439                     709100
## 4 Arizona  0.899          0.649            0.393                    7004300
## 5 Arkansas 0.701          0.431            0.238                    2921300
## 6 Califor… 0.903          0.671            0.433                   38745900
## # … with 1 more variable: Average_Monthly_SNAP_Participants &lt;chr&gt;</code></pre>
</div>
<div id="tidying-and-combining-data" class="section level2">
<h2>Tidying and Combining Data</h2>
<p>I then began tidying the data. While the SNAP dataset was already tidy, the Breastfed part of the new full dataset needs to be pivoted. I also recoded the time-based values to give them shorter names, renamed a few of the columns, and removed the &quot;Footnotes&quot; column which was simply a remnant of the data I used.</p>
<pre class="r"><code>fullset &lt;- fullset %&gt;% pivot_longer(2:4, names_to = &quot;Timepoint&quot;, 
    values_to = &quot;Proportion&quot;) %&gt;% mutate(Timepoint = recode(Timepoint, 
    Ever_Breastfed = &quot;Any_time&quot;, Breastfeeding_at_6_months = &quot;6_months&quot;, 
    Breastfeeding_at_12_months = &quot;12_months&quot;)) %&gt;% mutate(Footnotes = NULL) %&gt;% 
    rename(SNAPavg = Average_Monthly_SNAP_Participants, Population = Total_Residents, 
        PropBreastfed = Proportion)
head(fullset)</code></pre>
<pre><code>## # A tibble: 6 x 5
##   Location      Population SNAPavg  Timepoint PropBreastfed
##   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;        
## 1 United States  318498500 39651687 Any_time  0.841        
## 2 United States  318498500 39651687 6_months  0.583        
## 3 United States  318498500 39651687 12_months 0.353        
## 4 Alabama          4752600 766681   Any_time  0.69         
## 5 Alabama          4752600 766681   6_months  0.385        
## 6 Alabama          4752600 766681   12_months 0.216</code></pre>
<p>I also needed to change the values of average monthly SNAP participants and the proportion breastfed from characters to integers.</p>
<pre class="r"><code>fullset %&gt;% mutate(SNAPavg = as.numeric(SNAPavg), PropBreastfed = as.numeric(PropBreastfed))</code></pre>
<pre><code>## # A tibble: 162 x 5
##    Location      Population  SNAPavg Timepoint PropBreastfed
##    &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;             &lt;dbl&gt;
##  1 United States  318498500 39651687 Any_time          0.841
##  2 United States  318498500 39651687 6_months          0.583
##  3 United States  318498500 39651687 12_months         0.353
##  4 Alabama          4752600   766681 Any_time          0.69 
##  5 Alabama          4752600   766681 6_months          0.385
##  6 Alabama          4752600   766681 12_months         0.216
##  7 Alaska            709100    91995 Any_time          0.919
##  8 Alaska            709100    91995 6_months          0.674
##  9 Alaska            709100    91995 12_months         0.439
## 10 Arizona          7004300   845733 Any_time          0.899
## # … with 152 more rows</code></pre>
</div>
<div id="creating-summary-statistics" class="section level2">
<h2>Creating Summary Statistics</h2>
<p>I began by creating a new variable that describes the proportion of residents who receive SNAP benefits in a state.</p>
<pre class="r"><code>fullset &lt;- fullset %&gt;% mutate(SNAPavg = as.numeric(SNAPavg), 
    PropBreastfed = as.numeric(PropBreastfed)) %&gt;% mutate(SNAPprop = SNAPavg/Population)
head(fullset)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   Location      Population  SNAPavg Timepoint PropBreastfed SNAPprop
##   &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt;
## 1 United States  318498500 39651687 Any_time          0.841    0.124
## 2 United States  318498500 39651687 6_months          0.583    0.124
## 3 United States  318498500 39651687 12_months         0.353    0.124
## 4 Alabama          4752600   766681 Any_time          0.69     0.161
## 5 Alabama          4752600   766681 6_months          0.385    0.161
## 6 Alabama          4752600   766681 12_months         0.216    0.161</code></pre>
<p>I wanted to learn more about this new variable that I created, so I poked around a bit.</p>
<pre class="r"><code>fullset %&gt;% group_by(Location) %&gt;% distinct(SNAPprop) %&gt;% arrange(desc(SNAPprop)) %&gt;% 
    head()</code></pre>
<pre><code>## # A tibble: 6 x 2
## # Groups:   Location [6]
##   Location            SNAPprop
##   &lt;chr&gt;                  &lt;dbl&gt;
## 1 U.S. Virgin Islands    0.307
## 2 Guam                   0.271
## 3 New Mexico             0.223
## 4 Louisiana              0.192
## 5 West Virginia          0.183
## 6 Mississippi            0.175</code></pre>
<pre class="r"><code>fullset %&gt;% group_by(Location) %&gt;% distinct(SNAPprop) %&gt;% arrange(SNAPprop) %&gt;% 
    head()</code></pre>
<pre><code>## # A tibble: 6 x 2
## # Groups:   Location [6]
##   Location      SNAPprop
##   &lt;chr&gt;            &lt;dbl&gt;
## 1 Wyoming         0.0523
## 2 Utah            0.0609
## 3 New Hampshire   0.0660
## 4 North Dakota    0.0720
## 5 Kansas          0.0772
## 6 Minnesota       0.0782</code></pre>
<p><em>From this, it appears that the US Virgin Islands, Guam, and New Mexico have the highest proportion of people receiving SNAP benefits, while Wyoming, Utah, and New Hampshire have the lowest.</em></p>
<p>I continued exploring the rest of this dataset by looking at the summary statistics for all of my numeric variables, including the column I just created. Since the data for the United States overall would artifically inflate the mean of several variables, I also included the median.</p>
<pre class="r"><code>fullset %&gt;% summarize_if(is.numeric, list(median = median, mean = mean, 
    sd = sd), na.rm = T) %&gt;% pivot_longer(1:12, names_to = &quot;Statistic&quot;, 
    values_to = &quot;Values&quot;) %&gt;% separate(Statistic, into = c(&quot;Data&quot;, 
    &quot;Statistic&quot;))</code></pre>
<pre><code>## # A tibble: 12 x 3
##    Data          Statistic        Values
##    &lt;chr&gt;         &lt;chr&gt;             &lt;dbl&gt;
##  1 Population    median     4215550     
##  2 SNAPavg       median      585064     
##  3 PropBreastfed median           0.581 
##  4 SNAPprop      median           0.124 
##  5 Population    mean      11801293.    
##  6 SNAPavg       mean       1510608.    
##  7 PropBreastfed mean             0.593 
##  8 SNAPprop      mean             0.130 
##  9 Population    sd        42838810.    
## 10 SNAPavg       sd         5382404.    
## 11 PropBreastfed sd               0.212 
## 12 SNAPprop      sd               0.0464</code></pre>
<p><em>The extent to which the US's population and SNAP average changes the mean is very clear if you compare the median and mean values for Population and SNAPavg, as well as the standard deviation. Disregarding these, the other means are higher than the medians, indicating the dataset is likely skewed right.</em></p>
<p>I then chose to look at summary statistics for the proportion of breastfed babies when grouped by timepoint.</p>
<pre class="r"><code>fullset %&gt;% group_by(Timepoint) %&gt;% summarize(median = median(PropBreastfed, 
    na.rm = T), max = max(PropBreastfed, na.rm = T), min = min(PropBreastfed, 
    na.rm = T), mean = mean(PropBreastfed, na.rm = T))</code></pre>
<pre><code>## # A tibble: 3 x 5
##   Timepoint median   max   min  mean
##   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 12_months  0.36  0.55  0.203 0.359
## 2 6_months   0.581 0.791 0.385 0.585
## 3 Any_time   0.842 0.953 0.662 0.836</code></pre>
<p><em>This revealed that the greatest difference between the minimum and maximum states occurred at the six month timepoint, so I chose to explore that further.</em></p>
<p>I filtered the dataset so that it only showed the six month timepoint, and returned only the rows where the proportion of babies that were breastfed was greater than 0.581, which was the median.</p>
<pre class="r"><code>fullset %&gt;% select(Location, Timepoint, PropBreastfed) %&gt;% filter(Timepoint == 
    &quot;6_months&quot;, PropBreastfed &gt; 0.581) %&gt;% arrange(desc(PropBreastfed))</code></pre>
<pre><code>## # A tibble: 26 x 3
##    Location     Timepoint PropBreastfed
##    &lt;chr&gt;        &lt;chr&gt;             &lt;dbl&gt;
##  1 Minnesota    6_months          0.791
##  2 Washington   6_months          0.746
##  3 Hawaii       6_months          0.745
##  4 Virginia     6_months          0.74 
##  5 Oregon       6_months          0.734
##  6 Vermont      6_months          0.704
##  7 South Dakota 6_months          0.701
##  8 Colorado     6_months          0.692
##  9 Alaska       6_months          0.674
## 10 California   6_months          0.671
## # … with 16 more rows</code></pre>
<p><em>This returned 26 rows, or half of the dataset. In looking at this, I was looking for signs of correlation between the states with the lowest proportion of SNAP recipients and the highest proportion of breastfed babies. Earlier, I found that Wyoming, Utah, and New Hampshire have the lowest proportion of people receiving SNAP benefits. These states were all represented in this half of the dataset, although they were not in the top 10 states with the highest proprtion of breastfed babies at six months.</em></p>
<p>I next did the same filtering process, but this time I returned only the rows where the proprtion of breastfed babies was less than 0.581.</p>
<pre class="r"><code>fullset %&gt;% select(Location, Timepoint, PropBreastfed) %&gt;% filter(Timepoint == 
    &quot;6_months&quot;, PropBreastfed &lt; 0.581) %&gt;% arrange(PropBreastfed)</code></pre>
<pre><code>## # A tibble: 26 x 3
##    Location      Timepoint PropBreastfed
##    &lt;chr&gt;         &lt;chr&gt;             &lt;dbl&gt;
##  1 Alabama       6_months          0.385
##  2 Mississippi   6_months          0.386
##  3 Louisiana     6_months          0.41 
##  4 West Virginia 6_months          0.426
##  5 Arkansas      6_months          0.431
##  6 Kentucky      6_months          0.445
##  7 Indiana       6_months          0.47 
##  8 Guam          6_months          0.475
##  9 Tennessee     6_months          0.487
## 10 Missouri      6_months          0.502
## # … with 16 more rows</code></pre>
<p><em>The US Virgin Islands, Guam, and New Mexico had the highest proportions of people receiving SNAP benefits. The US Virgin Islands did not record breastfeeding data; Guam and New Mexico are both in this half of the dataset, but New Mexico has a higher proportion of breastfed babies at six months (0.579) than Guam (0.475).</em></p>
</div>
<div id="creating-visualizations" class="section level2">
<h2>Creating Visualizations</h2>
<p>I began by making a correlation heatmap of my numeric variables. To simplify this, I chose to only represent one timepoint, six months.</p>
<pre class="r"><code>cormat &lt;- fullset %&gt;% filter(Timepoint==&quot;6_months&quot;) %&gt;% select_if(is.numeric) %&gt;% cor(use=&quot;pair&quot;)
cormat %&gt;% as.data.frame %&gt;% rownames_to_column(&quot;var1&quot;) %&gt;% pivot_longer(-1, &quot;var2&quot;, values_to=&quot;correlation&quot;) %&gt;%
  ggplot(aes(var1, var2, fill=correlation)) + geom_tile() +
scale_fill_gradient2(low=&quot;red&quot;,mid=&quot;white&quot;,high=&quot;blue&quot;)+ #makes colors!
geom_text(aes(label=round(correlation,2)),color = &quot;black&quot;, size = 4)+ #overlays correlation values
theme(axis.text.x = element_text(angle = 90, hjust = 1))+ #flips the x-axis labels
coord_fixed()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /> <em>Most notably, this shows that there is a perfect positive correlation between the average monthly number of SNAP recipients and the population of a state. More interestingly, there is also a negative correlation between the proportion of SNAP recipients and the proportion of infants who are breastfed at six months.</em></p>
<p>Next, I plotted the proportion of SNAP recipients against the proportion of breastfed infants in each state. I colored the points by the breastfeeding timepoints. I also added linear regression lines to better visualize the trends.</p>
<pre class="r"><code>fullset %&gt;% ggplot(aes(SNAPprop, PropBreastfed)) + geom_point(aes(color = Timepoint)) + 
    geom_smooth(aes(group = Timepoint, color = Timepoint), method = lm, 
        se = F)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" /> <em>This shows that there is a negative correlation between the proportion of SNAP recipients and the proportion of breastfed infants at all timepoints, which supports my expectations.</em></p>
<p>I then tried to visualize this trend by overlaying a bar plot of the proportion of SNAP recipients in each state onto a boxplot of the proportion of breastfed infants in each state.</p>
<pre class="r"><code>fullset %&gt;% ggplot(aes(x = Location)) + geom_boxplot(aes(y = PropBreastfed), 
    color = &quot;grey50&quot;) + geom_bar(aes(y = SNAPprop), stat = &quot;summary&quot;, 
    fun = mean, fill = &quot;mistyrose3&quot;) + theme(axis.text.x = element_text(angle = 45, 
    hjust = 1))</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;" /> <em>In general, states with high proportions of SNAP recipients (tall bars) tend to have lower proprtions of breastfed infants (lower boxplots). The inverse is also true. This relationship, however, is not perfect.</em></p>
</div>
<div id="pam-of-numeric-variables" class="section level2">
<h2>PAM of numeric variables</h2>
<p>Lastly, I decided to perform PAM clustering on my numeric variables to see if they would result in any interesting clusters. I began by separating my numeric variables; once again, I chose to represent only the six months timepoint to ease interpretation of the data, and I removed the statistics for the US in general using filter, as leaving them in would result in a cluster with only the US.</p>
<pre class="r"><code>library(cluster)
fullset_values &lt;- fullset %&gt;% filter(Timepoint == &quot;6_months&quot;) %&gt;% 
    select(2:3, 5:6) %&gt;% na.omit() %&gt;% filter(Population &lt; 3e+08)</code></pre>
<p>Next, I needed to determine how many clusters to use. To do this, I graphed the silhouette widths, and found that two clusters would be best.</p>
<pre class="r"><code>sil_width &lt;- vector()  #empty vector to hold mean sil width
for (i in 2:10) {
    kms &lt;- kmeans(fullset_values, centers = i)  #compute k-means solution
    sil &lt;- silhouette(kms$cluster, dist(fullset_values))  #get sil widths
    sil_width[i] &lt;- mean(sil[, 3])  #take averages (higher is better)
}
ggplot() + geom_line(aes(x = 1:10, y = sil_width)) + scale_x_continuous(name = &quot;k&quot;, 
    breaks = 1:5)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>I performed PAM clustering on my numeric variables with two clusters.</p>
<pre class="r"><code>pam1 &lt;- fullset_values %&gt;% pam(k = 2)</code></pre>
<p>I then looked at the summary statistics by cluster for each of my numeric variables.</p>
<pre class="r"><code>fullset_values %&gt;% mutate(cluster = pam1$clustering) %&gt;% group_by(cluster) %&gt;% 
    rename_all(function(x) str_replace(x, &quot;_&quot;, &quot;&quot;)) %&gt;% summarize_if(is.numeric, 
    .funs = list(mean = mean, median = median, sd = sd), na.rm = T) %&gt;% 
    pivot_longer(contains(&quot;_&quot;)) %&gt;% separate(name, sep = &quot;_&quot;, 
    into = c(&quot;variable&quot;, &quot;stat&quot;)) %&gt;% pivot_wider(names_from = &quot;variable&quot;, 
    values_from = &quot;value&quot;) %&gt;% arrange(stat)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   cluster stat   Population  SNAPavg PropBreastfed SNAPprop
##     &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;
## 1       1 mean     3171897.  394013.        0.583    0.127 
## 2       2 mean    15162946. 1954247.        0.595    0.128 
## 3       1 median   2952350   379890         0.589    0.121 
## 4       2 median  11355900  1556452         0.580    0.131 
## 5       1 sd       2113000.  277156.        0.104    0.0450
## 6       2 sd       9260067. 1156981.        0.0813   0.0241</code></pre>
<p><em>Clustering appears to have been based on the population of the states and the average number of SNAP recipients. Cluster 1 looks like smaller states with lower numbers of SNAP recipients, and cluster 2 looks like larger states with higher numbers of SNAP recipients. Given the high correlation between average SNAP recipients and population that I found in my heat map above, these clusters do not seem very informative in determining any relationships between the proportion of infants that were breastfed and the number of SNAP recipients in each state. There is very little difference between clusters for both the proportion of breastfed infants and the proportion of SNAP recipients.</em></p>
<p>I then visualized my cluster assignments using the package GGally.</p>
<pre class="r"><code>library(GGally)
ggpairs(fullset_values, aes(color = as.factor(pam1$clustering)))</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;" /> <em>It confirms what I had thought based on the summary statistics. Cluster 2 is made up of high-population states with high numbers of SNAP recipients, and cluster 1 is made up of low-population states with low numbers of SNAP recipients. The breastfeeding data was not very informative; this is evident in looking at the graph showing the proportion of breastfed infants and the proportion of SNAP recipients. While clustering is certainly a powerful tool, I think that it is better suited for a different type of dataset. If I had more proportion-based data, I think that this would do better.</em></p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
